### ISSUE TITLE
Problem while compiling

### ISSUE THREAD

**Issue by qbai22** [harjot-oberai/Croller#4]
I cant compile through you guide because of error 

Error:Could not GET 'https://dl.bintray.com/sdsmdg/Croller/com/sdsmdg/harjot/croller/1.0.0/croller-1.0.0.pom'. Received status code 403 from server: Forbidden

**Comment by harjot-oberai** [comment]
Can you please try again. I am able to compile the library in a new project without any issues.

**Comment by qbai22** [comment]
![error](https://cloud.githubusercontent.com/assets/14185390/23341223/12199504-fc65-11e6-92c7-96843e48b2e4.png)
![error2](https://cloud.githubusercontent.com/assets/14185390/23341227/1885453c-fc65-11e6-80a2-32953e6050ce.png)

tried again - nothing changes. Even when i click to this link 'https://dl.bintray.com/sdsmdg/Croller/com/sdsmdg/harjot/croller/1.0.0/croller-1.0.0.pom' in my browser i got "Forbidden" signature

**Comment by harjot-oberai** [comment]
OK, the issue was with my bintray account. I unknowingly chose the "Trial" version instead of the "open source" one. Hopefully it will shifted to an open source account, in a day or two. 
Till then you can copy the Croller.java from : [here](https://github.com/harjot-oberai/Croller/blob/master/croller/src/main/java/com/sdsmdg/harjot/crollerTest/Croller.java) and paste it in  your main java project directory.
Also copy attrs.xml from : [here](https://github.com/harjot-oberai/Croller/blob/master/croller/src/main/res/values/attrs.xml) and paste it under **/res/values/**<br/>
Now you can use the library as you like.

**Comment by harjot-oberai** [comment]
Updated the bintray account 👍 . New instructions added in the README.
